---
- name: Install cURL
  apt: pkg=curl state=latest
    
- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /opt/scripts
    - /var/run/telegraf

- name: Copy telegraf package
  copy:
    src: 
         telegraf_1.10.4-1_amd64.deb
    dest: /opt/scripts/telegraf_1.10.4-1_amd64.deb
    owner: root
    group: root
    mode: 0644

- name: Install Telegraf
  apt:
    deb: /opt/scripts/telegraf_1.10.4-1_amd64.deb
    state: present
    
- name: Change User of Telegraf Log Directory
  file:
    path: /var/log/telegraf/
    owner: telegraf
    group: telegraf
    mode: 0755

- name: Create nightwatch command
  set_fact:
     nightwatch_configs: "{{ nightwatch_configs }} --config /etc/filebeat/configs/{{ item }}.yml"
  with_items:
      "{{ configs_list }}"

- name: Copy telegraf.yml  and 20-dashbase.yml files
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'templates/telegraf.yml.j2', dest: '/etc/telegraf/telegraf.conf' } 
    - { src: 'templates/20-dashbase.yml.j2', dest: '/etc/telegraf/telegraf.d/20-dashbase.conf' } 

- name: Copy night-watch deb
  copy:
    src: night-watch_{{ nightwatch_version }}-rc4_Linux_64-bit.deb
    dest: /opt/scripts/night-watch_{{ nightwatch_version }}-rc4_Linux_64-bit.deb
    owner: root
    group: root
    mode: 0644

- name: Install night-watch
  apt:
    deb: /opt/scripts/night-watch_{{ nightwatch_version }}-rc4_Linux_64-bit.deb
    state: present

- name: Retart Telegraf Service
  service: 
    name: telegraf
    state: restarted

- name: Create Prometheus pushgateway crontab
  cron:
    name: "telegraf pushgateway"
    job: "curl -s {{ prometheus_local_exporter_url }} | curl -k --connect-timeout 10 --data-binary @- {{ prometheus_pushgateway_url }} &> /dev/null"
  when:
    - prometheus_pushgateway_enable

