filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log

# https://www.elastic.co/guide/en/beats/filebeat/6.6/configuration-template.html
setup.template.enabled: false

output.elasticsearch:
  hosts: ["http://proxy.127.0.0.1.xip.io:80"]
  index: "logs"