apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: freeswitch
    component: call
  name: freeswitch-success-call
spec:
  selector:
    matchLabels:
      app: freeswitch
      component: call
  replicas: 1
  template:
    metadata:
      labels:
        app: freeswitch
        component: call
    spec:
      containers:
        - name: caller
          image: dashbase/sip-cmd-phone
          args: [
            "-u", "1005", "-p", "testpassword", "-d", "freeswitch-internal:15060", "--call", "1006"
          ]
        - name: receiver
          image: dashbase/sip-cmd-phone
          args: [
            "-u", "1006", "-p", "testpassword", "-d", "freeswitch-internal:15060", "--auto-answer"
          ]
