{
 "title": "Filebeat Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "label_values(http_filebeat_events_active, host)"
   },
   {
    "name": "table",
    "query": "label_values(http_filebeat_events_active, table)"
   }
  ]
 },
 "panels": [
  { "title": "Filebeat Input vs Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Local Probe - Write Rate",
   "type": "graph",
   "description": "Dashbase Night-Watch Probe\n\nhttps://github.com/dashbase/night-watch",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(nightwatch_metric_file_append_total_size{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}[5m])",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "nightwatch-metric",
     "select": [
      [
       { "params": [ "file-append-total-size" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Filebeat Final Output Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(http_libbeat_output_write_bytes{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}[5m])",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "http",
     "query": "SELECT difference(\"libbeat_output_write_bytes\") FROM \"http\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "libbeat_output_write_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Harvesters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Harvesters Running",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "http_filebeat_harvester_running{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "http",
     "select": [
      [
       { "params": [ "filebeat_harvester_running" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Harvesters Skipped/Truncated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "skipped - $tag_host",
     "expr": "http_filebeat_harvester_skipped{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "skipped - {{ host }}",
     "measurement": "http",
     "select": [
      [
       { "params": [ "filebeat_harvester_skipped" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "truncated - $tag_host",
     "expr": "http_filebeat_input_log_files_truncated{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "truncated - {{ host }}",
     "measurement": "http",
     "select": [
      [
       {
        "params": [
         "filebeat_input_log_files_truncated"
        ],
        "type": "field"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Internal Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Events Added",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(http_filebeat_events_added{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}[5m])",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "http",
     "select": [
      [
       { "params": [ "filebeat_events_added" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Events Active",
   "type": "graph",
   "description": "Number of events being worked on.",
   "gridPos": { "h": 9, "w": 10, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "http_filebeat_events_active{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "http",
     "select": [
      [
       { "params": [ "filebeat_events_active" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Events Done",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(http_filebeat_events_done{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}[5m])",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "http",
     "query": "SELECT difference(\"filebeat_events_done\") FROM \"http\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "filebeat_events_done" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Filebeat Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Output Event Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(http_libbeat_output_events_active{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}[5m])",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "http",
     "select": [
      [
       { "params": [ "libbeat_output_events_active" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Filebeat Final Output Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(http_libbeat_output_events_acked{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}[5m])",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "http",
     "query": "SELECT difference(\"libbeat_output_events_acked\") FROM \"http\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "libbeat_output_events_acked" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Output Error Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "read - $tag_host",
     "expr": "rate(http_libbeat_output_read_errors{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}[1m])",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "read - {{ host }}",
     "measurement": "http",
     "select": [
      [
       { "params": [ "libbeat_output_read_errors" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "write - $tag_host",
     "expr": "rate(http_libbeat_output_write_errors{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}[1m])",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "write - {{ host }}",
     "measurement": "http",
     "select": [
      [
       { "params": [ "libbeat_output_write_errors" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "http_system_load_norm_5{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "http",
     "select": [
      [
       { "params": [ "system_load_norm_5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "http_beat_memstats_memory_alloc{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "http",
     "select": [
      [
       { "params": [ "beat_memstats_memory_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}