{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(dashbase_table_info, app)"
   },
   {
    "name": "topic",
    "query": "label_values(kafka_server_brokertopicmetrics_messagesin_total{app='$app'},topic)"
   }
  ]
 },
 "panels": [
  { "title": "Input / Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total Bytes I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total Messages In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m]))",
     "legendFormat": "received by kafka"
    },
    {
     "expr": "sum(proxy:events_sent:sum{topic=~'${topic:pipe}',app='$app'})",
     "legendFormat": "sent from proxy"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_requestchannel_requestqueuesize{component=\"kafka\",app='$app'})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(kafka_network_requestchannel_requestqueuesize{component=\"kafka\",app='$app'})",
     "legendFormat": "response "
    }
   ]
  },
  {
   "title": "Bytes Rejected Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesrejected_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Produce/Fetch Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalproducerequests_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m])) by (topic)",
     "legendFormat": "produce - {{topic}}"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalfetchrequests_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m])) by (topic)",
     "legendFormat": "fetch - {{topic}}"
    }
   ]
  },
  { "title": "Log Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "log size by topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{app=\"$app\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "log size by broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{app=\"$app\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{component=\"kafka\",app='$app'}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_bytes_used{area='heap',component=\"kafka\",app='$app'})",
     "legendFormat": "used - {{instance}}"
    },
    {
     "expr": "(jvm_memory_bytes_max{area='heap',component=\"kafka\",app='$app'})",
     "legendFormat": "max - {{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{component=\"kafka\",app='$app'}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}