{
 "title": "Dashbase Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "cluster",
    "query": "label_values(dashbase_table_info, app)"
   },
   {
    "name": "table",
    "query": "label_values(dashbase_table_info{app='$app'}, table)"
   },
   {
    "name": "hostname",
    "query": "label_values(http_filebeat_events_active, host)"
   },
   { "name": "duration", "query": "1m,5m,15m" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "#Uptime\nmin(\n  label_replace(\n    (kube_statefulset_labels{label_dashbase_io=\"true\",label_app=\"$app\"} * on (statefulset, instance) group_right \n      label_replace (\n        ( time()- kube_pod_start_time{exported_namespace=\"$app\",pod=~\"^(.+)-[0-9]$\"} \n      ), \"statefulset\", \"$1\", \"pod\", \"^(.+)-[0-9]$\")\n    ), \"component\", \"$1\", \"statefulset\", \"(.+)\")\n  ) by (component)\nor\nmin(\n  label_replace(\n    (kube_deployment_labels{label_dashbase_io=\"true\",label_app=\"$app\"} * on (deployment, instance) group_right \n      label_replace (\n        ( time()- kube_pod_start_time{exported_namespace=\"$app\",pod=~\"^(.+)-[A-Fa-f0-9]+-[A-za-z0-9]+$\"} \n      ), \"deployment\", \"$1\", \"pod\", \"^(.+)-[A-Fa-f0-9]+-[A-za-z0-9]+$\") \n    ), \"component\", \"$1\", \"deployment\", \"(.+)\")\n  ) by (component)"
    },
    {
     "expr": "sum(label_replace (kube_deployment_labels{label_dashbase_io=\"true\",label_app=\"$app\"} * on (deployment,exported_namespace,instance) (kube_deployment_status_replicas_available), \"component\", \"$1\", \"deployment\", \"(.+)\") ) by (component)\nor\nsum(label_replace (kube_statefulset_labels{label_dashbase_io=\"true\",label_app=\"$app\"} * on (statefulset,exported_namespace,instance) (kube_statefulset_status_replicas_ready), \"component\", \"$1\", \"statefulset\", \"(.+)\") ) by (component)"
    },
    {
     "expr": "sum(label_replace (kube_deployment_labels{label_dashbase_io=\"true\",label_app=\"$app\"} * on (deployment,exported_namespace,instance) (kube_deployment_status_replicas_available == bool on(deployment,exported_namespace,instance) kube_deployment_spec_replicas), \"component\", \"$1\", \"deployment\", \"(.+)\") ) by (component)\nor\nsum(label_replace (kube_statefulset_labels{label_dashbase_io=\"true\",label_app=\"$app\"} * on (statefulset,exported_namespace,instance) (kube_statefulset_status_replicas_ready == bool on(statefulset,exported_namespace,instance) kube_statefulset_replicas), \"component\", \"$1\", \"statefulset\", \"(.+)\") ) by (component)"
    }
   ]
  },
  {
   "title": "Table Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count(dashbase_actual_retention_days{app=\"$app\",table=~\"${table:pipe}$\"}) by (table)"
    },
    {
     "expr": "#Num CPUs\nsum(jvm_cpu_num_processors{app=\"$app\",table=~\"${table:pipe}$\"}) by (table)"
    },
    {
     "expr": "#Total disk \nsum(dashbase_disk_total_bytes{app=\"$app\",table=~\"${table:pipe}$\"}) by  (table)"
    },
    {
     "expr": "#Disk Used\nsum(dashbase_disk_total_bytes{app=\"$app\",table=~\"$table$\"} - dashbase_disk_available_bytes{app=\"$app\",table=~\"$table$\"}) by (table) "
    },
    {
     "expr": "#Disk Available \nsum(dashbase_disk_available_bytes{app=\"$app\",table=~\"$table$\"}) by (table)  #origin query\n"
    },
    {
     "expr": "#Disk Usage \n avg(1 - (dashbase_disk_available_bytes{app=\"$app\",table=~\"${table:pipe}$\"}  / dashbase_disk_total_bytes{app=\"$app\",table=~\"${table:pipe}$\"}) ) by (table)  #origin query"
    },
    {
     "expr": "#Retention Days \navg(dashbase_actual_retention_days{app=\"$app\",table=~\"${table:pipe}$\"}) by (table)"
    },
    {
     "expr": "#Doc Count \nsum(dashbase_total_num_docs{app=\"$app\",table=~\"${table:pipe}$\"}) by (table)"
    },
    {
     "expr": "#Raw produced(24)\nsum(increase(nightwatch_metric_file_append_total_size{table=~\"$table$\"}[24h])) by (table)"
    },
    {
     "expr": "#Raw Received \nsum(filebeat:original_bytes_received:increase:sum{app=\"$app\",table=~\"${table:pipe}$\"}) by (table)"
    },
    {
     "expr": "#Data Indexed \nsum(increase(dashbase_indexer_bytes_total{app=\"$app\",table=~\"${table:pipe}$\"}[24h])) by (table)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "errors observed from Dashbase services",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_proxy_events_parse_error_total{app='$app'}[$duration])) by (topic) > 0",
     "legendFormat": "proxy {{topic}} - parse error"
    },
    {
     "expr": "proxy:kafka_failure:sum{app='$app'} > 0",
     "legendFormat": "proxy - kafka failure"
    },
    {
     "expr": "proxy:overflow_message:sum{app='$app'} > 0",
     "legendFormat": "message overflow"
    },
    {
     "expr": "sum(rate(dashbase_index_event_parse_error{table=~'${table:pipe}',app='$app'}[$duration])) by (table) > 0",
     "legendFormat": "table {{table}} - input parse error"
    },
    {
     "expr": "sum(rate(io_dashbase_http_es_IndexResource_bulkPost_exceptions_total{table=~'${table:pipe}',app='$app'}[$duration])) by (table) > 0",
     "legendFormat": "table {{table}} - input rest exception"
    },
    {
     "expr": "sum(rate(dashbase_parse_error_total{table=~'${table:pipe}',app='$app'}[$duration])) by (table) > 0",
     "legendFormat": "table {{table}} - index parse error"
    },
    {
     "expr": "sum(rate(dashbase_parse_skipped_total{table=~'${table:pipe}',app='$app'}[$duration])) by (table) > 0",
     "legendFormat": "table {{table}} - skipped"
    },
    {
     "expr": "rate(dashbase_api_partition_errors_total{root=~'${table:pipe}',app='$app'}[$duration]) + rate(dashbase_api_partition_timeouts_total{root=~'${table:pipe}',app='$app'}[$duration]) > 0",
     "legendFormat": "api - error calling tables"
    },
    {
     "expr": "proxy:bulk_post_exception:sum{app='$app'} > 0",
     "legendFormat": "proxy - exception"
    }
   ]
  },
  {
   "title": "Ingestion / Index",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_ingestion_bytes_total{table=~'${table:pipe}',app='$app'}[$duration])) by (instance)",
     "legendFormat": "bytes indexed {{instance}}"
    },
    {
     "expr": "avg(rate(dashbase_indexer_bytes_total{table=~'${table:pipe}',app='$app'}[$duration])) by (instance)",
     "legendFormat": "bytes ingested {{instance}}"
    }
   ]
  },
  {
   "title": "Ingestion Delay",
   "type": "graph",
   "description": "Delay from event produce until searchable",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_indexer_full_latency_secs_sum{table=~'${table:pipe}',app='$app'}[$duration]) / rate(dashbase_indexer_full_latency_secs_count{table=~'${table:pipe}',app='$app'}[$duration])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_search_query_latency_secs_sum{table=~'${table:pipe}',app='$app'}[$duration]) / rate(dashbase_search_query_latency_secs_count{table=~'${table:pipe}',app='$app'}[$duration])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}