dashbase_version: 1.0.1


#ingress:
#  enabled: true
#  host: "your-cluster-name.your-domain"

https: false

default_storageclass_provider:
  platform: "gce"
#  parameter:  Uncomment for the platforms that support encrypted
#    encrypted: "true"

enablePodPriority: true

accounts:
  prometheus: true

kube-state-metrics:
  enabled: true

default:
  priorityClassName: dashbase-normal-priority
  storage:
    class: dashbase-meta

  table:
    priorityClassName: dashbase-high-priority
    storage:
      class: dashbase-data
      size: 500Gi
    environment:
      JAVA_OPTS: -Xmx4g -Xms2g
      BLOOM_FILTER_SIZE: 400
      MAX_BUFFER_DELAY_IN_SEC: 90
      RETENTION_NUM_DAYS: 7
      RETENTION_SIZE_GB: 400
      IN_MEMORY_BUFFER: true
      READER_CACHE_MEM_PERCENT: 60
      NUM_INDEXING_THREADS: 2
      MIN_BUFFER_SIZE_MB: 2000


services:
  etcd:
    enabled: true

  api:
    enabled: true

  web:
    enabled: true

  grafana:
    enabled: true

  prometheus:
    enabled: true
    storage:
      size: 100Gi

  #pushgateway:
  #  enabled: true

tables:
  logs:
    replicas: 1
