---
- name: Transfer and execute a script.
  hosts: "filebeat_hosts"
  become: yes
  become_method: sudo
  roles:
    - telegraf
    - filebeat
    - role: heplify
      when: '"heplify" in vars.configs.split(",")'

  vars_prompt:
    - name: "dashbase_url"
      prompt: "Enter Dashbase Table URL"
      private: no
    - name: "configs"
      prompt: "Enter comma separated list of filebeat configs without .yml (for example: freeswitch,syslog)"
      private: no

  vars:
    filebeat_version: "oss-7.6.1"
    prometheus_pushgateway_enable: True
    configs_list: "{{ configs.split(',') }}"
    table: "logs"
    pushgateway_url: "{{ dashbase_url.split('//')[0] }}//pushgateway.{{ dashbase_url.split('.')[1:] | join('.') | regex_replace(':(\\d+)$') }}"
    prometheus_local_exporter_url: http://localhost:29273/metrics
    prometheus_pushgateway_url: "{{ pushgateway_url }}/metrics/job/filebeat/instance/{{ ansible_hostname }}"
    nightwatch_version: 1.1.1
    nightwatch_configs: ""
    heplify_version: 1.57-rc1
    heplify_args: ""
