---
- name: Transfer and execute a script.
  hosts: "logstash_hosts"
  become: yes
  become_method: sudo
  roles:
    - logstash

  vars_prompt:
    - name: "dashbase_url"
      prompt: "Enter Dashbase Table URL"
      private: no
    - name: "configs"
      prompt: "Enter comma separated list of logstash input plugins which needs dependencies to install (for example: mysql)"
      private: no

  vars:
    logstash_version: "oss-7.6.1"
    configs_list: "{{ configs.split(',') }}"
    table: "logs"

    netsapiens_1:
      connection_string: "jdbc:mysql://localhost:3306/database"
      user: "logstash"
      password: "logstash"

    netsapiens_2:
      connection_string: "jdbc:mysql://localhost:3306/database"
      user: "logstash"
      password: "logstash"
