---
- name: Transfer and execute a script.
  hosts: logstash_hosts
  become: yes
  become_method: sudo
  tasks:

     - name: Stop Logstash Service
       service:
        name: logstash
        state: stopped


