apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-key-server-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 1m

    scrape_configs:
      - job_name: 'dashbase-key-metrics'
        scrape_interval: 15s

        honor_labels: true
        metrics_path: '/federate'

        params:
          'match[]':
            - '{__name__=~"dashbase:.*"}'

        static_configs:
          - targets:
            - prometheus:9090

#    remote_write:
#      - url: "http://storage-adapter-service.dashbase.svc.cluster.local/receive"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dashbase
    component: prometheus-key-server
  name: prometheus-key-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashbase
      component: prometheus-key-server
  template:
    metadata:
      labels:
        app: dashbase
        component: prometheus-key-server
    spec:
      containers:
        - image: prom/prometheus:v2.8.0
          imagePullPolicy: Always
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/healthy
              port: 9090
              scheme: HTTP
          name: prometheus
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-key-server-config
              readOnly: true
              subPath: prometheus.yml
            - name: prometheus-key-server-storage
              mountPath: /prometheus/
      volumes:
        - configMap:
            defaultMode: 0777
            name: prometheus-key-server-config
          name: prometheus-key-server-config
        - name: prometheus-key-server-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dashbase
    component: prometheus-key-server
  name: prometheus-key-server
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: dashbase
    component: prometheus-key-server
  type: ClusterIP
