apiVersion: v1
kind: Service
metadata:
  name: admindash
spec:
  ports:
    - name: "ssh"
      port: 22
      targetPort: 22
      protocol: TCP
    - name: server
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: dashbase
    component: installer
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: admindash
  labels:
    app: dashbase
    component: installer
spec:
  serviceName: admindash
  replicas: 1
  selector:
    matchLabels:
      app: dashbase
      component: installer
  template:
    metadata:
      labels:
        app: dashbase
        component: installer
    spec:
      serviceAccountName: dashadmin
      containers:
        - name: admindash
          #image: dashbase/dashbase-admin:chaotest
          image: dashbase/dashbase-admin-server:nightly
          imagePullPolicy: Always
          command: ["flask", "run", '--host=0.0.0.0']
          env:
            - name: INCLUSTER_CONFIG
              value: "true"
            - name: PATH_VALUES_YML
              value: "/data/dashbase-values.yaml"
          volumeMounts:
            - mountPath: /data
              name: admindash-vol

  volumeClaimTemplates:
    - metadata:
        name: admindash-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
