apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: remote
spec:
  clusterIP:
  ports:
  - name: admin
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: http
    port: 9876
    protocol: TCP
    targetPort: 9876
  - name: presto
    port: 9090
    protocol: TCP
    targetPort: 9090
  type: ExternalName
  externalName: api-internal.dashbase.svc.cluster.local
