apiVersion: v1
kind: Service
metadata:
  labels:
    app: dashbase
    component: api
    dashbase.io: "true"
  name: api-internal
  namespace: dashbase
spec:
  clusterIP: None
  ports:
  - name: admin
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: http
    port: 9876
    protocol: TCP
    targetPort: 9876
  - name: presto
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: dashbase
    component: api
  sessionAffinity: None
  type: ClusterIP
