apiVersion: v1
kind: ConfigMap
metadata:
  name: dashbasemetrics-config
data:
  exporter.yml: |-
    metrics:
      error_count:
        description: "count of logs with level:error"
        table: "logs"
        aggregation: "count(*)"
      sip_status_codes:
        description: "breakdown of sip status codes"
        table: "freeswitch"
        accumulate: true
        filter: "type:sip"
        aggregation: "topn(status-code, 20, topn(hostname, 100))"
      pct_mos_score:
        description: "percentile audio mos score"
        table: "freeswitch"
        filter: "type:cdr AND _missing_:variables.originator"
        accumulate: false
        aggregation: "topn(hostname, 100, pct(callStats.audio.inbound.mos, 50, 90, 99))"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashbasemetrics
  labels:
    app: dashbasemetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashbasemetrics
  template:
    metadata:
      labels:
        app: dashbasemetrics
      annotations:
        dashbase.io/scrape: "true"
        dashbase.io/metric_path: "/metrics"
        dashbase.io/scrape_port: "8989"
    spec:
      containers:
        - name: exporter
          image: dashbase/exporter:nightly
          imagePullPolicy: Always
          args: ['/etc/exporter.yml']
          env:
            - name: API_URL
              value: https://api.dashbase.svc:9876
          volumeMounts:
          - name: config
            mountPath: /etc/exporter.yml
            readOnly: true
            subPath: exporter.yml
      volumes:
        - name: config
          configMap:
            defaultMode: 0600
            name: dashbasemetrics-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dashbasemetrics
  name: dashbasemetrics
spec:
  ports:
  - name: "exporter"
    port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app: dashbasemetrics
  sessionAffinity: None
  type: ClusterIP
