dashbase_version: 1.0.1-rc1

# License information
username: "your-dashbase-username"
license: "your-dashbase-license"

ingress:
  enabled: true
  host: "your-cluster-name.your-domain"

https: false

default_storageclass_provider:
  platform: "your-platform (aws, gce, azure)"
#  parameter:  Uncomment for the platforms that support encrypted
#    encrypted: "true"

enablePodPriority: true

accounts:
  prometheus: true

kube-state-metrics:
  enabled: true

default:
  priorityClassName: dashbase-normal-priority
  storage:
    class: dashbase-meta
  containerConfig:
    resources:
      requests:
        cpu: 1
        memory: 2G
      limits:
        cpu: 2
        memory: 2G
  table:
    priorityClassName: dashbase-high-priority
    storage:
      class: dashbase-data
      size: 4000Gi
    containerConfig:
      resources:
          requests:
            cpu: 7.5
            memory: 50G
          limits:
            cpu: 7.5
            memory: 50G
    environment:
      JAVA_OPTS: -Xmx32g -Xms8g
      BLOOM_FILTER_SIZE: 400
      MAX_BUFFER_DELAY_IN_SEC: 90
      RETENTION_NUM_DAYS: 7
      RETENTION_SIZE_GB: 3400
      IN_MEMORY_BUFFER: true
      READER_CACHE_MEM_PERCENT: 60
      NUM_INDEXING_THREADS: 2
      MIN_BUFFER_SIZE_MB: 2000


services:
  etcd:
    enabled: true

  api:
    enabled: true

  web:
    enabled: true

  grafana:
    enabled: true

  prometheus:
    enabled: true
    storage:
      size: 100Gi

  pushgateway:
    enabled: true

tables:
  your-table-name:
    replicas: 1
