---
- name: Transfer and execute a script.
  hosts: freeswitch
  become: yes
  become_method: sudo
  tasks:

     - name: Create Check script file
       copy:
        src: "check_collector_status.sh"
        dest: "/tmp/check_collector_status.sh"
        owner: root
        group: root
        mode: 0755

     - name: Run the collector process check script
       shell: /tmp/check_collector_status.sh
       
