- paths:
    - /var/log/asterisk/full
  type: log
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: after
  close_inactive: 90s
  harvester_limit: 1000
  scan_frequency: 1s
  symlinks: true
  clean_removed: true
  fields:
    _message_parser:
      type: grok
      pattern: "\\[%{TIMESTAMP_ISO8601:timestamp:datetime:yyyy-MM-dd HH:mm:ss}\\] %{WORD:level:meta}\\[%{INT:lwp:int}\\] %{JAVAFILE:source:meta}: %{GREEDYDATA:message}"
      messageParser:
        type: sip

- paths:
    - /var/log/asterisk/freepbx.log
    - /var/log/asterisk/freepbx_security.log
  type: log
  close_inactive: 90s
  harvester_limit: 1000
  scan_frequency: 1s
  symlinks: true
  clean_removed: true
  fields:
    _message_parser:
      type: "timestamp"
      format: "yyyy-MMM-dd HH:mm:ss"
      scan: "true"
