- paths:
    - /var/log/heplify.log
  type: log
  multiline.pattern: '^20'
  multiline.negate: true
  multiline.match: after
  close_inactive: 90s
  harvester_limit: 1000
  scan_frequency: 1s
  symlinks: true
  clean_removed: true
  fields:
    x-dashbase-component: heplify
    _message_parser:
      type: multi
      parsers_list:
        - name: heplify
          config:
            type: multi
            applyAll: 'true'
            parsers:
              heplify_grok:
                type: grok
                pattern: "%{DATA:timestamp:datetime} %{WORD:level:meta} HEP packet:\\{Version:%{WORD:capture.version:text},Protocol:%{WORD:capture.protocol:text},SrcIP:%{IPORHOST:capture.src.ip:text},DstIP:%{IPORHOST:capture.dst.ip:text},SrcPort:%{INT:capture.src.port:text},DstPort:%{INT:capture.dst.port:text},Tsec:%{INT:capture.tsec:int},Tmsec:%{INT:capture.tmsec:int},ProtoType:%{WORD:capture.proto.type:text},NodeID:%{WORD:capture.node.id:text},NodePW:(?:%{DATA:capture.node.pw:text}|),CID:(?:%{DATA:capture.cid:text}|),Vlan:(?:%{WORD:capture.vlan:text}|)\\} with Payload:%{GREEDYDATA:message}"
                timestamp:
                  format: iso
              heplify_sip:
                type: sip
                sortedFields: call-id
        - name: basic
          config:
            type: timestamp
            scan: 'true'
            format: iso
