- type: log
  paths:
    - /var/log/ep-signaling-*.log
    - /var/log/mub-signaling-*.log
  fields:
    _message_parser:
      type: multi
      applyAll: 'true'
      parsers:
        grok:
          type: grok
          pattern: '%{TIMESTAMP_ISO8601_NANO:timestamp:datetime}\|%{DATA:component:meta}\[%{INT:lwp:int}\]\|(?:%{DATA:call-id})\|%{DATA:val1}\|%{INT:val2:int}\|%{GREEDYDATA:message}'
        sip:
          type: sip
          sortedFields: call-id,user-agent

  multiline.pattern: ^\d{4}-\d{2}-\d{2}
  multiline.negate: true
  multiline.match: after
  close_inactive: 90s
  harvester_limit: 5000
  scan_frequency: 1s
  symlinks: true
  clean_removed: true

