apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dashbase-meta
parameters:
  encrypted: "true"
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
