kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dashbase-indexer-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
reclaimPolicy: Delete
volumeBindingMode: Immediate
