- name: create filebeat config directory
  file:
    path: /etc/filebeat/configs
    state: directory
    owner: root
    group: root
    mode: 0755

## Copy app related config files
- name: Copy filebeat app config files
  template:
    src: "configs/{{ item }}.yml"
    dest: "/etc/filebeat/configs/"
  with_items:
    "{{ configs_list }}"

##copy filebeat fields.yml
- name: Copy fields file
  copy:
    src: fields.yml
    dest: /etc/filebeat/fields.yml

## Copy the filebeat config file
- name: Copy filebeat.yml file
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600

- name: Stop Filebeat Service
  service:
    name: filebeat
    state: stopped

- name: Wait for monitoring port to stop listening
  shell: sleep 5

- name: Restart Filebeat Service
  service:
    name: filebeat
    state: started
