# https://www.elastic.co/guide/en/beats/filebeat/7.6/running-with-systemd.html
- name: Create systemd config directory for filebeat
  file:
    path: /etc/systemd/system/filebeat.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy systemd config file for filebeat
  copy:
    src: filebeat.systemd.conf
    dest: /etc/systemd/system/filebeat.service.d/filebeat.systemd.conf

- name: Create filebeat config directory
  file:
    path: /etc/filebeat/configs
    state: directory
    owner: root
    group: root
    mode: 0755

## Copy app related config files
- name: Copy filebeat app config files
  copy:
    src: "templates/configs/{{ item }}.yml"
    dest: "/etc/filebeat/configs/{{ item }}.yml"
  with_items:
    "{{ configs_list | difference(filebeat_modules) }}"

## Delete existed app related config file which is already defined in modules
- name: Delete redundant filebeat app config files
  file:
    path: "/etc/filebeat/configs/{{ item }}.yml"
    state: absent
  with_items:
    "{{ configs_list | intersect(filebeat_modules) }}"

## Copy module related config files
- name: Copy filebeat module config files
  copy:
    src: "module/{{ item }}"
    dest: "/usr/share/filebeat/module/"
  with_items:
    "{{ configs_list | intersect(filebeat_modules) }}"

##copy filebeat fields.yml
- name: Copy fields file
  copy:
    src: fields.yml
    dest: /etc/filebeat/fields.yml

## Copy the filebeat config file
- name: Copy filebeat.yml file
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600

- name: Stop Filebeat Service
  service:
    name: filebeat
    state: stopped

- name: Wait for monitoring port to stop listening
  shell: sleep 5

- name: Restart Filebeat Service
  service:
    name: filebeat
    state: started
