---

- include_tasks: RedHat.yml
  when:
    - ansible_os_family == "RedHat"

- include_tasks: Debian.yml
  when:
    - ansible_os_family == "Debian"

- include_tasks: freeswitch.yml
  when: '"freeswitch" in configs_list'

- include_tasks: Configure.yml
