apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    clusterName: '{{ $labels.clusterName }}'
    regionName: '{{ $labels.regionName }}'
  labels:
    app: prometheus-operator
    role: dashbase-telegraf
  name: dashbase-telegraf
spec:
  groups:
    - name: telegraf
      rules:
        - expr: rate(push_time_seconds[15m]) == 0
          annotations:
            summary: "Missing Telegraf metrics from '{{ $labels.exported_instance }}'"
            description: "No Telegraf metrics received from '{{ $labels.exported_instance }}' in the last 15 minutes. Please check Telegraf on this host or if this was intentional, delete the corresponding group from Pushgateway."
          labels:
            severity: critical
          for: 5m
          alert: missing_telegraf_metrics
