type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
fields_under_root: true
json.keys_under_root: true
json.add_error_key: true
close_inactive: 90s
harvester_limit: 1000
scan_frequency: 1s
symlinks: true
clean_removed: true
fields:
  type: cdr

processors:
  - copy_fields:
      fields:
        - from: variables.sip_user_agent
          to: user-agent
      fail_on_error: false
      ignore_missing: true
