type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
fields_under_root: true
json.keys_under_root: true
json.add_error_key: true
close_inactive: 90s
harvester_limit: 1000
scan_frequency: 1s
symlinks: true
clean_removed: true
fields:
  type: cdr

processors:
  - add_locale: ~
  - rename:
      when:
        has_fields: ['fields._message_parser']
      fields:
        - from: "beat.timezone"
          to: "fields._message_parser.defaultTimeZone"
  - rename:
      fields:
        - from: "beat.hostname"
          to: "hostname"
  - drop_fields:
      fields: ["offset", "beat", "prospector", "host", "input"]
