- paths:
   - /var/log/freeswitch/freeswitch.log
   - /usr/local/freeswitch/log/freeswitch.log
  type: log
  multiline.pattern: '^(?:[A-Fa-f0-9]{8}-(?:[A-Fa-f0-9]{4}-){3}[A-Fa-f0-9]{12} )?\d{4}-\d{2}-\d{2}|^(?:[A-Fa-f0-9]{8}-(?:[A-Fa-f0-9]{4}-){3}[A-Fa-f0-9]{12} )?EXECUTE|^(?:[A-Fa-f0-9]{8}-(?:[A-Fa-f0-9]{4}-){3}[A-Fa-f0-9]{12} )?Dialplan|^recv|^send'
  multiline.negate: true
  multiline.match: after
  close_inactive: 90s
  harvester_limit: 1000
  scan_frequency: 1s
  symlinks: true
  clean_removed: true
  fields:
    _message_parser:
      type: multi
      parsers_list:
      - name: freeswitch
        config:
          type: grok
          pattern: "(?:%{UUID:uuid:text} |)%{TIMESTAMP_ISO8601:timestamp:datetime:yyyy-MM-dd HH:mm:ss.SSSSSS} \\[%{WORD:level:meta}\\] %{JAVAFILE:source:meta}:%{INT:line:int} %{GREEDYDATA:message}"
      - name: sip
        config:
          type: multi
          applyAll: 'true'
          parsers:
            sip_timestamp:
              type: timestamp
              scan: 'true'
              format: HH:mm:ss.SSS
            sip_sip:
              type: sip
      - name: universal
        config:
          type: grok
          pattern: "(?:%{UUID:uuid:text} |)%{GREEDYDATA:message}"

- paths:
   - /var/log/freeswitch/json_cdr/*/*.cdr.json
   - /usr/local/freeswitch/log/json_cdr/*/*.cdr.json
  type: log
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true
  close_inactive: 90s
  harvester_limit: 1000
  scan_frequency: 1s
  symlinks: true
  clean_removed: true
  fields:
    type: cdr
