#=========================== Filebeat inputs =============================
filebeat.inputs:

- type: log
  enabled: true

  # Glob based paths.
  paths:
    #- 'C:\Logfiles\CLSLog-*'
    - '/Users/narsky/c/unifysquare/clslog-1.log'

  close_inactive: 90s
  harvester_limit: 1000
  scan_frequency: 1s
  symlinks: true
  clean_removed: true
  fields:
    _message_parser:
      type: multi
      parsers_list:

        - name: sipone
          config:
            type: grok
            pattern: |-
              %{DATA:level:meta}\(%{DATA:flag:meta}\) \[%{DATA:machine:meta}\]%{BASE16NUM:process}\.%{BASE16NUM:thread}::%{NOTSPACE:timestamp:datetime:MM/dd/yyyy-HH:mm:ss.SSS}\.%{BASE16NUM:sequence-num} \(%{DATA:component:meta},%{DATA:source}\) (\[%{DATA:correlation-id}\])?
              [>]+%{DATA:message-header}
              %{GREEDYDATA:message}
            subParsers:
              message:
                type: sip
                sortedFields: "call-id,user-agent"

        - name: siptwo
          config:
            type: grok
            pattern: |-
              %{DATA:level:meta}\(%{DATA:flag:meta}\) \[%{DATA:machine:meta}\]%{BASE16NUM:process}\.%{BASE16NUM:thread}::%{NOTSPACE:timestamp:datetime:MM/dd/yyyy-HH:mm:ss.SSS}\.%{BASE16NUM:sequence-num} \(%{DATA:component:meta},%{DATA:source}\) (\[%{DATA:correlation-id}\])?%{DATA:message-header}
              Start-Line: %{GREEDYDATA:message}
            subParsers:
              message:
                type: sip
                sortedFields: "call-id,user-agent"

        - name: universal
          config:
            type: grok
            pattern: |-
              %{DATA:level:meta}\(%{DATA:flag:meta}\) \[%{DATA:machine:meta}\]%{BASE16NUM:process}\.%{BASE16NUM:thread}::%{NOTSPACE:timestamp:datetime:MM/dd/yyyy-HH:mm:ss.SSS}\.%{BASE16NUM:sequence-num} \(%{DATA:component:meta},%{DATA:source}\) (\[%{DATA:correlation-id}\])?%{GREEDYDATA:message}

  multiline.pattern: ^TL_
  multiline.negate: true
  multiline.match: after
  
#================================ Processors =====================================
# Drop metadata added by Filebeat to save bandwidth as it's unnecessary

processors:
  - add_locale: ~
  - rename:
      when:
        has_fields: ['fields._message_parser']
      fields:
        - from: "event.timezone"
          to: "fields._message_parser.defaultTimeZone"
  - rename:
      fields:
        - from: "agent.hostname"
          to: "hostname"
  - drop_fields:
      fields: ["host", "input", "ecs", "agent", "event"]

#==================== Elasticsearch template setting ==========================
setup.template:
  name: "logs"
  pattern: "logs"
  fields: "fields.yml"
  overwrite: true

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  bulk_max_size: 3000
  worker: 30
  compression_level: 5
  hosts: "DASHBASE_URL:443"
  protocol: "https"
  ssl.verification_mode: "none"

#================================ Logging =====================================

# Available log levels are: error, warning, info, debug
logging.level: info
