dashbase_version: nightly-a675c6

https: true

#default_storageclass_provider:
#  platform: "aws"

default:
  storage:
    class: "dashbase-meta"
    size: 10Gi
  containerConfig:
    resources:
      requests:
        cpu: 100m
        memory: 1G
      limits:
        cpu: 1
        memory: 2G
  table:
    priorityClassName: dashbase-high-priority
    storage:
      class: "dashbase-data"
      size: "100Gi"

    containerConfig:
      resources:
        requests:
          cpu: 1
          memory: 2G
        limits:
          cpu: 1
          memory: 2G
    environment:
      JAVA_OPTS: "-Xmx2g -Xms2g"
      BLOOM_FILTER_SIZE: "400"
      MAX_BUFFER_DELAY_IN_SEC: "1000"
      RETENTION_NUM_DAYS: "14"
      RETENTION_SIZE_GB: "2500"
      IN_MEMORY_BUFFER: "true"
      READER_CACHE_MEM_PERCENT: "60"
      NUM_INDEXING_THREADS: "2"
      MIN_BUFFER_SIZE_MB: "200"

presto:
  enabled: false
  presto:
    prestoKeystorePassword: PRESTO_KEYSTORE_PASSWORD
    dashbaseKeystorePassword: DASHBASE_KEYSTORE_PASSWORD

ingress:
  enabled: true
  certmanager: false
  host: test.dashbase.local

tables:
  logs:
      replicas: 1

services:
  etcd:
    enabled: true
  api:
    enabled: true
  web:
    enabled: true
  prometheus:
    enabled: true
    image: "dashbase/prometheus:nightly"
    environment:
      ENABLE_KUBERNETES_SCRAPE: "true"
      ENABLE_KUBERNETES_NODES_SCRAPE: "true"
  grafana:
    enabled: true
  alertmanager:
    enabled: false
  pushgateway:
    enabled: true
