dashbase_version: nightly

https: true

default_storageclass_provider:
  platform: "aws"

default:
  storage:
    class: "dashbase-meta"
    size: 10Gi

  table:
    priorityClassName: dashbase-high-priority
    storage:
      class: "dashbase-data"
      size: "1000Gi"

    containerConfig:
      resources:
        requests:
          cpu: 1
          memory: 2G
        limits:
          cpu: 1
          memory: 2G
    environment:
      JAVA_OPTS: "-Xmx20g -Xms16g"
      BLOOM_FILTER_SIZE: "400"
      MAX_BUFFER_DELAY_IN_SEC: "1000"
      RETENTION_NUM_DAYS: "14"
      RETENTION_SIZE_GB: "850"
      IN_MEMORY_BUFFER: "true"
      READER_CACHE_MEM_PERCENT: "60"
      NUM_INDEXING_THREADS: "2"
      MIN_BUFFER_SIZE_MB: "200"

ingress:
  enabled: true
  certmanager: false
  host: test.dashbase.io

tables:
  logs:
      replicas: 1

presto:
  enabled: true
  presto:
    prestoKeystorePassword: PRESTO_KEYSTORE_PASSWORD
    dashbaseKeystorePassword: DASHBASE_KEYSTORE_PASSWORD
    coordinatorResources:
      requests:
        cpu: 1
        memory: 1G
      limits:
        cpu: 1
        momory: 1G

services:
  etcd:
    enabled: true
  api:
    enabled: true

  web:
    enabled: true
    expose: false
    secrets:
      presto-cert:
        dir: /run/prestojks/
        file: presto-cert.pem
      presto-key:
        dir: /run/prestojks/
        file: presto-key.pem
      presto-keystore:
        dir: /run/prestojks/
        file: presto-keystore
      presto-keystore-password:
        dir: /run/prestojks/
        file: presto-keystore-password
#    containerConfig:
#      resources:
#        limits:
#          cpu: 1
#          memory: 2G
#        requests:
#          cpu: 500m
#          memory: 2G
    environment:
      ENABLE_SEARCH_SCHEDULER: "true"
      ENABLE_CHRONOLOGICAL_SORT: "true"
#      INTERNAL_TOKEN: "internal-token-XXXXXXXXXXXXXXXXX"
#      AUTH_URL: "https://auth.mynamespace.domain.com"
      ENABLE_SCHEDULED_METRICS: "true"
#      ENABLE_BANNER_MESSAGE: "Welcome to Dashbase Staging environment where things break more often than not. Don't try to use this for a demo unless you know the consequences. https://web.release.dashbase.io"
#      JAVA_OPTS: -Xmx1500m -Xms1500m
#      SMTP_HOST: "smtp.gmail.com"
#      SMTP_USERNAME: "no-reply@dashbase.io"
#      SMTP_PASSWORD: "dashbasenoreplyemail"
#      SMTP_PROTOCOL: "smtps"
      DISPLAY_COLOREDFIELDS: "traceId,spanId,level"
      ENABLE_UCAAS: "true"
      UCAAS_PRESTO_URL: "jdbc:presto://presto-coordinator-0.presto-coordinator.dashbase.svc.cluster.local:8443/thrift/dashbase?user=test&password=&SSL=true&SSLKeyStorePath=/run/prestojks/presto-keystore&SSLKeyStorePassword=PRESTO_KEYSTORE_PASSWORD"
      ENABLE_CDR: "true"
      CDR_TABLES: "logs"

  prometheus:
    enabled: true
    image: "dashbase/prometheus:nightly"
  grafana:
    enabled: true
    image: dashbase/grafana:23dfde
  alertmanager:
    enabled: false
  pushgateway:
    enabled: true
  exporter:
    enabled: true
    config:
      metrics:
        error_count:
          description: "count of logs with level:error"
          table: "logs"
          filter: "level:error"
          aggregation: "count(*)"
          accumulate: true
