apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    clusterName: '{{ $labels.clusterName }}'
    regionName: '{{ $labels.regionName }}'
  labels:
    role: dashbase-collection-rules
  name: dashbase-collection-rules
spec:
  groups:
    - name: dashbase-collection
      rules:
        - expr: http_filebeat_harvester_running > 3000
          annotations:
            summary: "Filebeat Harvesters greater than 3000 on {{ $labels.host }}"
            description: "Filebeat on {{ $labels.host }} has more than 3000 harvesters and is backed up. Check Dashbase for any ingest issues."
          for: 5m
          alert: filebeat_harvester_running
        - expr: rate(http_libbeat_output_events_dropped[5m])/rate(http_libbeat_output_events_total[5m]) > 0.01
          annotations:
            summary: "Filebeat on {{ $labels.host }} is dropping events"
            description: "Filebeat on {{ $labels.host }} is dropping events. Check the Filebeat logs for more information."
          labels:
            severity: critical
          for: 5m
          alert: filebeat_events_dropped
        - expr: rate(http_filebeat_harvester_skipped[5m]) > 0
          annotations:
            summary: "Filebeat backed up on {{ $labels.host }}"
            description: "Filebeat on {{ $labels.host }} is backed up and skipping log files. Check Dashbase for any ingest issues."
          labels:
            severity: critical
          for: 5m
          alert: filebeat_harvester_skipped
        - expr: rate(http_beat_info_uptime_ms[15m]) == 0
          annotations:
            summary: "Missing Filebeat metrics from '{{ $labels.host }}'"
            description: "No Filebeat metrics received from '{{ $labels.host }}' in the last 15 minutes. Please check the Filebeat running on this host or if this was intentional, delete the corresponding group from Pushgateway."
          labels:
            severity: critical
          for: 5m
          alert: missing_filebeat_metrics
        - expr: rate(nightwatch_metric_run_spent_time_nanosecond[15m]) == 0
          annotations:
            summary: "Missing NightWatch metrics from '{{ $labels.host }}'"
            description: "No NightWatch metrics received from '{{ $labels.host }}' in the last 15 minutes. Please check NightWatch on this host or if this was intentional, delete the corresponding group from Pushgateway."
          labels:
            severity: critical
          for: 5m
          alert: missing_nightwatch_metrics
        - expr: rate(push_time_seconds[15m]) == 0
          annotations:
            summary: "Missing Telegraf metrics from '{{ $labels.exported_instance }}'"
            description: "No Telegraf metrics received from '{{ $labels.exported_instance }}' in the last 15 minutes. Please check Telegraf on this host or if this was intentional, delete the corresponding group from Pushgateway."
          labels:
            severity: critical
          for: 5m
          alert: missing_telegraf_metrics 
