- name: Copy MySQL java connector
  copy:
    src: mysql-connector-java_8.0.19-1ubuntu16.04_all.deb
    dest: /opt/scripts/mysql-connector-java_8.0.19-1ubuntu16.04_all.deb
    owner: root
    group: root
    mode: 0644

- name: Install MySQL java connector
  apt:
    deb: /opt/scripts/mysql-connector-java_8.0.19-1ubuntu16.04_all.deb
    state: present
