filebeat.registry_flush: 30s
filebeat.registry.flush: 30s
filebeat.prospectors:
- paths:
   - /TO/CHANGE/YOUR/LOCAL/LOG/PATH
  input_type: log
  close_inactive: 90s
  harvester_limit: 5000
  scan_frequency: 1s
  symlinks: true
  clean_removed: true
  fields:
    _message_parser:
      type: grok
      pattern: '%{GREEDYDATA:message}'

queue.mem:
  events: 180000
  flush.min_events: 3000

processors:
  - add_locale: ~
  - rename:
      fields:
        - from: "beat.timezone"
          to: "fields._message_parser.defaultTimeZone"
        - from: "beat.hostname"
          to: "hostname"
  - drop_fields:
      fields: ["offset", "beat", "prospector", "host", "input"]

# https://www.elastic.co/guide/en/beats/filebeat/6.6/configuration-template.html
setup.template.enabled: false

output.elasticsearch:
  hosts: ["/TO/CHANGE/YOUR/DASHBASE/(TABLE/PROXY)/HOST/WITH/PORT"]
  index: "/TO/CHANGE/YOUR/DASHBASE/TABLE/NAME"
  bulk_max_size: 3000
  worker: 30
  compression_level: 5
  protocol: "/TO/CHANGE/YOUR/DASHBASE/(TABLE/PROXY)/PROTOCOL"

http.enabled: true
http.host: 127.0.0.1
http.port: 1050
