dashbase_version: nightly

https: true

default_storageclass_provider:
  platform: "aws"

default:
  labels: {}
  storage:
    class: dashbase-meta
    size: 10Gi

ingress:
  enabled: true
  certmanager: false
  host: test.dashbase.io

tables:
  logs:
      replicas: 1
      storage:
         class: dashbase-data
         size: 1000Gi
      environment:
         JAVA_OPTS: "-Xmx4g -Xms2g"

services:
  etcd:
    enabled: true
  api:
    enabled: true
  web:
    enabled: true
  prometheus:
    enabled: true
    image: "dashbase/prometheus:nightly"
  grafana:
    enabled: true
  alertmanager:
    enabled: false
  pushgateway:
    enabled: true
