dashbase_version: nightly

https: true

default_storageclass_provider:
  platform: "aws"

default:
  storage:
    class: "dashbase-meta"
    size: 10Gi

  table:
    priorityClassName: dashbase-high-priority
    storage:
      class: "dashbase-data"
      size: "1000Gi"

    containerConfig:
      resources:
        requests:
          cpu: 2
          memory: 26G
        limits:
          cpu: 2
          memory: 28G
    environment:
      JAVA_OPTS: "-Xmx20g -Xms16g"
      BLOOM_FILTER_SIZE: "400"
      MAX_BUFFER_DELAY_IN_SEC: "1000"
      RETENTION_NUM_DAYS: "14"
      RETENTION_SIZE_GB: "850"
      IN_MEMORY_BUFFER: "true"
      READER_CACHE_MEM_PERCENT: "60"
      NUM_INDEXING_THREADS: "2"
      MIN_BUFFER_SIZE_MB: "200"

ingress:
  enabled: true
  certmanager: false
  host: test.dashbase.io

tables:
  logs:
      replicas: 1

presto:
  enabled: false
  presto:
    prestoKeystorePassword: PRESTO_KEYSTORE_PASSWORD
    dashbaseKeystorePassword: DASHBASE_KEYSTORE_PASSWORD
    coordinatorResources:
      requests:
        cpu: 1
        memory: 1G
      limits:
        cpu: 1
        momory: 1G

services:
  etcd:
    enabled: true
  api:
    enabled: true
  web:
    enabled: true
  prometheus:
    enabled: true
    image: "dashbase/prometheus:nightly"
  grafana:
    enabled: true
  alertmanager:
    enabled: false
  pushgateway:
    enabled: true
